# 🛡️ Snort Intrusion Prevention System (IPS) Implementation

## 📌 Project Overview

This project demonstrates the deployment and configuration of **Snort**, an open-source network security tool used for **Intrusion Detection and Intrusion Prevention**.

The lab focuses on installing Snort, configuring the network monitoring environment, creating custom rules, and testing the system by generating alerts through suspicious network activity.

This work was completed during my **Cybersecurity Internship at CoreTech Innovations in collaboration with ORIC QUEST Nawabshah**.

---

# 🎯 Objectives

The goals of this lab were:

* Understand the concept of **Intrusion Prevention Systems (IPS)**
* Install and configure **Snort on a Linux virtual machine**
* Monitor network traffic
* Create custom Snort detection rules
* Generate alerts using test traffic
* Analyze logs generated by Snort

---

# 🔐 What is an IPS?

An **Intrusion Prevention System (IPS)** is a network security tool that monitors network traffic and automatically **detects and blocks malicious activities**.

| IDS              | IPS                        |
| ---------------- | -------------------------- |
| Detects attacks  | Detects + Blocks attacks   |
| Generates alerts | Prevents malicious traffic |

Snort can operate in **both IDS and IPS modes**.

---

# ⚙️ Installation & Setup

### Step 1 — Update the System

```bash
sudo apt update
sudo apt upgrade
```

---

### Step 2 — Install Snort

```bash
sudo apt install snort -y
```

During installation, Snort asks for **HOME_NET configuration**.

Example:

```
192.168.1.0/24
```

---

# 💻 Commands Used

```bash
# Check Snort version
snort -V

# Identify network interface
ip a

# Run Snort in IDS mode
sudo snort -A console -q -c /etc/snort/snort.conf -i eth0
```

| Option     | Purpose                    |
| ---------- | -------------------------- |
| -A console | Display alerts on terminal |
| -q         | Quiet mode                 |
| -c         | Specify configuration file |
| -i         | Network interface          |

---

# 🧩 Configuration

Main configuration file:

```
/etc/snort/snort.conf
```

Open configuration file:

```bash
sudo nano /etc/snort/snort.conf
```

Define local network:

```
ipvar HOME_NET 192.168.1.0/24
```

---

# 🧠 Custom Rule Creation

Local rule file:

```
/etc/snort/rules/local.rules
```

Example rule to detect **ICMP Ping traffic**:

```
alert icmp any any -> $HOME_NET any (msg:"Ping Detected"; sid:1000001; rev:1;)
```

This rule generates an alert whenever ping traffic is detected.

---

# 🏗️ Snort Architecture

Snort works using several core components:

### 1️⃣ Packet Decoder

Captures network packets from the interface.

### 2️⃣ Preprocessors

Prepare and normalize traffic before inspection.

Examples include:

* Fragmentation handling
* Protocol normalization
* Packet reassembly

### 3️⃣ Detection Engine

Matches network traffic against rule signatures.

### 4️⃣ Logging & Alert System

Stores alerts when suspicious activity is detected.

### 5️⃣ Output Modules

Saves logs into files or monitoring systems.

---

# 🧪 Testing the System

To test the rule, a ping request was sent:

```bash
ping 192.168.1.5
```

Snort successfully detected the ICMP traffic and generated the following alert:

```
[**] [1:1000001:1] Ping Detected [**]
```

---

# 📂 Log Files

Snort stores logs in:

```
/var/log/snort/
```

Log information includes:

* Source IP
* Destination IP
* Protocol type
* Timestamp
* Alert details

---

# ⚠️ Challenges Faced

During implementation the following issues occurred:

* Identifying the correct network interface
* Configuring the correct HOME_NET value
* Loading custom rules properly
* Running Snort with correct permissions

These problems were solved by verifying network configuration and reviewing documentation.

---

# 🛠 Tools & Technologies

| Tool            | Purpose              |
| --------------- | -------------------- |
| Snort           | Network IDS/IPS      |
| Linux           | Operating System     |
| Virtual Machine | Testing Environment  |
| Terminal        | System configuration |

---

# 📚 Learning Outcomes

After completing this lab I gained practical experience in:

* Intrusion Detection and Prevention Systems
* Installing and configuring Snort
* Writing custom Snort rules
* Monitoring and analyzing network traffic
* Understanding Snort architecture

---

# 👨‍💻 Author

**Syed Sardar Ali Shah**
Software Engineering Student — MUET SZAB Campus
Cybersecurity Intern — CoreTech Innovations

---

# 📜 License

This project is created for **educational and cybersecurity learning purposes**.
